# Generated by Django 3.2.7 on 2021-09-26 23:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210926_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.CharField(default='author', max_length=100),
        ),
    ]
