# Generated by Django 3.2.7 on 2021-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210926_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
