# Generated by Django 3.2.7 on 2021-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=30)),
                ('phoneNum', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('medicine', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('timeToTake', models.CharField(choices=[('1D', 'Once daily'), ('2D', 'Two times a day'), ('1N', 'Once nightly'), ('1W', 'Once a week'), ('EO', 'Once every other day')], default='1D', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numParticipants', models.IntegerField()),
                ('participantNames', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('store', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='activities',
            name='type',
            field=models.CharField(choices=[('SP', 'Sports'), ('ET', 'Entertainment'), ('MV', 'Movies'), ('GM', 'Games'), ('EX', 'Exercise'), ('HO', 'Hangout')], default='SP', max_length=2),
        ),
    ]
