# Generated by Django 3.2.7 on 2021-10-31 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_auto_20211031_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='health',
            name='author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopping',
            name='author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activities',
            name='type',
            field=models.CharField(choices=[('SP', 'Sports'), ('ET', 'Entertainment'), ('MV', 'Movies'), ('GM', 'Games'), ('EX', 'Exercise'), ('HO', 'Hangout'), ('HE', 'Health')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='health',
            name='phoneNum',
            field=models.IntegerField(),
        ),
    ]
