# Generated by Django 3.2.7 on 2021-10-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211031_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
