# Generated by Django 3.2.9 on 2021-11-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20211031_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event Title'),
        ),
    ]
