# Generated by Django 3.2.9 on 2021-11-28 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_activities_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.activities')),
            ],
        ),
    ]
