# Generated by Django 3.2.9 on 2021-11-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_activityreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='item_category',
            field=models.CharField(choices=[('Outdoor', 'Outdoor'), ('Entertainment', 'Entertainment'), ('Hygeine', 'Hygeine'), ('Food', 'Food'), ('Clothing', 'Clothing')], default='Food', max_length=20),
        ),
    ]
