# Generated by Django 3.2.9 on 2021-11-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_shopping_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='type',
            field=models.CharField(choices=[('Sport', 'Sports'), ('Entertainment', 'Entertainment'), ('Fitness', 'Exercise'), ('Hangout', 'Hangout'), ('Health', 'Health'), ('School', 'School'), ('Work', 'Work'), ('Other', 'Other')], default='Sport', max_length=20),
        ),
    ]
